### ISSUE TITLE
Error: No such file or directory: '/content/drive/My Drive/Colab Notebooks/face-smoothing/configs/configs.yaml'

### ISSUE THREAD

**Issue by OleksandrMyronchuk** [5starkarma/face-smoothing#2]
I got the following error:  '/content/drive/My Drive/Colab Notebooks/face-smoothing/configs/configs.yaml'

Here's the whole traceback:
```
python3 D:/Apps/face-smoothing/face-smoothing-main/infer.py --input 'D:/Data/Youtube/End/best.mp4' --output 'D:/Data/Youtube/End/op'
```

```
Traceback (most recent call last):
  File "D:\Apps\face-smoothing\face-smoothing-main\infer.py", line 147, in <module>
    main(args)
  File "D:\Apps\face-smoothing\face-smoothing-main\infer.py", line 79, in main
    cfg = load_configs()
          ^^^^^^^^^^^^^^
  File "D:\Apps\face-smoothing\face-smoothing-main\infer.py", line 69, in load_configs
    with open('/content/drive/My Drive/Colab Notebooks/face-smoothing'\
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/Colab Notebooks/face-smoothing/configs/configs.yaml'
```
 
Does it only work with Colab Notebooks? Please help to understand the error.

**Comment by 5starkarma** [comment]
Hi @OleksandrMyronchuk Sorry I can't be of more help. I wrote this a couple years ago and don't exactly know what the `.yml` file looks like anymore. It looks like I did build and run it in Colab but I am sure you could do it outside colab.
